In [1]:
import pandas as pd

In [28]:
df=pd.read_csv("/home/msis/aml_lab/data/bestsellers with categories.csv")
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [29]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [30]:
df.tail()

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [31]:
df.shape

(550, 7)

In [32]:
df.dtypes

Name               str
Author             str
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre              str
dtype: object

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 30.2 KB

In [34]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [35]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [71]:
X=df.iloc[:,1:-1].values
X

array([['JJ Smith', 4.7, 17350, 8, 2016],
       ['Stephen King', 4.6, 2052, 22, 2011],
       ['Jordan B. Peterson', 4.7, 18979, 15, 2018],
       ...,
       ['Jen Sincero', 4.7, 14331, 8, 2017],
       ['Jen Sincero', 4.7, 14331, 8, 2018],
       ['Jen Sincero', 4.7, 14331, 8, 2019]], shape=(550, 5), dtype=object)

In [72]:
y=df.iloc[:,-1].values
y

<StringArray>
['Non Fiction',     'Fiction', 'Non Fiction',     'Fiction', 'Non Fiction',
     'Fiction',     'Fiction',     'Fiction', 'Non Fiction',     'Fiction',
 ...
     'Fiction',     'Fiction',     'Fiction',     'Fiction',     'Fiction',
     'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction']
Length: 550, dtype: str

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
ct = ColumnTransformer(
    transformers=[
        ("author_enc", OneHotEncoder(handle_unknown='ignore'), [0]), # Author
        ("year_enc", OneHotEncoder(), [4]),                         # Year
        ("scaler", StandardScaler(), [1, 2, 3])                     # Rating, Reviews, Price
    ],
    remainder="drop" # or "passthrough" if you keep Name
)

X_transformed = ct.fit_transform(X)

In [79]:
pd.DataFrame(X_transformed).head()

                                                   0
0  <Compressed Sparse Row sparse matrix of dtype ...
1  <Compressed Sparse Row sparse matrix of dtype ...
2  <Compressed Sparse Row sparse matrix of dtype ...
3  <Compressed Sparse Row sparse matrix of dtype ...
4  <Compressed Sparse Row sparse matrix of dtype ...

In [80]:
import pandas as pd

# 1. Get the new column names generated by the ColumnTransformer
feature_names = ct.get_feature_names_out()

# 2. Convert the sparse matrix to a dense array and load it into a DataFrame
df_encoded = pd.DataFrame(X_transformed.toarray(), columns=feature_names)

# 3. View the first few rows
print(df_encoded.head())

   author_enc__x0_Abraham Verghese  author_enc__x0_Adam Gasiewski  \
0                              0.0                            0.0
1                              0.0                            0.0
2                              0.0                            0.0
3                              0.0                            0.0
4                              0.0                            0.0

   author_enc__x0_Adam Mansbach  author_enc__x0_Adir Levy  \
0                           0.0                       0.0
1                           0.0                       0.0
2                           0.0                       0.0
3                           0.0                       0.0
4                           0.0                       0.0

   author_enc__x0_Admiral William H. McRaven  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0

   author_enc__x0_Adult Coloring Book Designs  author_enc__x0_Alan Moore  \
0                                         0.0                        0.0
1                                         0.0                        0.0
2                                         0.0                        0.0
3                                         0.0                        0.0
4                                         0.0                        0.0

   author_enc__x0_Alex Michaelides  author_enc__x0_Alice Schertle  \
0                              0.0                            0.0
1                              0.0                            0.0
2                              0.0                            0.0
3                              0.0                            0.0
4                              0.0                            0.0

   author_enc__x0_Allie Brosh  ...  year_enc__x4_2013  year_enc__x4_2014  \
0                         0.0  ...                0.0                0.0
1                         0.0  ...                0.0                0.0
2                         0.0  ...                0.0                0.0
3                         0.0  ...                0.0                0.0
4                         0.0  ...                0.0                0.0

   year_enc__x4_2015  year_enc__x4_2016  year_enc__x4_2017  year_enc__x4_2018  \
0                0.0                1.0                0.0                0.0
1                0.0                0.0                0.0                0.0
2                0.0                0.0                0.0                1.0
3                0.0                0.0                1.0                0.0
4                0.0                0.0                0.0                0.0

   year_enc__x4_2019  scaler__x1  scaler__x2  scaler__x3
0                0.0    0.359990    0.460453   -0.470810
1                0.0   -0.080978   -0.844786    0.821609
2                0.0    0.359990    0.599440    0.175400
3                0.0    0.359990    0.808050   -0.655441
4                1.0    0.800958   -0.365880   -0.101547

[5 rows x 262 columns]

In [73]:
pd.DataFrame(X)

                            0    1      2   3     4
0                    JJ Smith  4.7  17350   8  2016
1                Stephen King  4.6   2052  22  2011
2          Jordan B. Peterson  4.7  18979  15  2018
3               George Orwell  4.7  21424   6  2017
4    National Geographic Kids  4.8   7665  12  2019
..                        ...  ...    ...  ..   ...
545               Jeff Kinney  4.9   9413   8  2019
546               Jen Sincero  4.7  14331   8  2016
547               Jen Sincero  4.7  14331   8  2017
548               Jen Sincero  4.7  14331   8  2018
549               Jen Sincero  4.7  14331   8  2019

[550 rows x 5 columns]

In [70]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Labelencoder_x1=LabelEncoder()
#X[:,0]=Labelencoder_x1.fit_transform(X[:,0])
X[:,4]=Labelencoder_x1.fit_transform(X[:,4])
print(X)

[['JJ Smith' 4.7 17350 8 7]
 ['Stephen King' 4.6 2052 22 2]
 ['Jordan B. Peterson' 4.7 18979 15 9]
 ...
 ['Jen Sincero' 4.7 14331 8 8]
 ['Jen Sincero' 4.7 14331 8 9]
 ['Jen Sincero' 4.7 14331 8 10]]

In [65]:
pd.DataFrame(X)

       0    1      2   3   4
0    114  4.7  17350   8   7
1    219  4.6   2052  22   2
2    134  4.7  18979  15   9
3     95  4.7  21424   6   8
4    174  4.8   7665  12  10
..   ...  ...    ...  ..  ..
545  120  4.9   9413   8  10
546  121  4.7  14331   8   7
547  121  4.7  14331   8   8
548  121  4.7  14331   8   9
549  121  4.7  14331   8  10

[550 rows x 5 columns]

In [66]:
Labelencoder_y=LabelEncoder()
y=Labelencoder_y.fit_transform(y) #since it's only one columns so use directly without using slicing
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])